remember_me: "1"
per_page: 10
limit_book: 5
size_image: 5
alert_size_image: "should be less than 5MB"
max_len: 50
min_len_pass: 6
action_type_comment: 1
action_type_review: 0
size_image_book: 140
size_image_avater: 100
max_len_name: 100
max_len_description: 150
max_rate: 5
max_size_avatar_show_review: 80
size_image_avatar_request: 40
min_rate: 1
